version: '3.8'
services:
  asignment2-service:
    build: ./asignment  # path is relative to docker-compose.yml localtion
    ports:
      - 5001:80  # host:container
    restart: always
  db:
    image: postgres
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: M_2d9307
       POSTGRES_DB: bian
    ports:
       - "5432:5432"
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    restart: always
